"""
配置模块

提供配置管理和常量定义
"""

from config.settings import Settings, settings
from config.constants import (
    # 日志配置
    MAX_LOG_ENTRIES,
    LOG_ROTATION_SIZE,
    LOG_RETENTION_DAYS,
    # 爬虫配置
    DEFAULT_PAGE_SIZE,
    MAX_EMPTY_PAGES,
    MAX_CONSECUTIVE_EMPTY,
    DEFAULT_CRAWL_DELAY,
    DEFAULT_MAX_PAGES,
    # 下载配置
    DEFAULT_CHUNK_SIZE,
    DEFAULT_MAX_THREADS,
    DEFAULT_MAX_RETRIES,
    DEFAULT_RETRY_DELAY,
    DEFAULT_TIMEOUT,
    # GUI配置
    GUI_REFRESH_INTERVAL_RUNNING,
    GUI_REFRESH_INTERVAL_IDLE,
    GUI_KEYWORD_MIN_LENGTH,
    GUI_KEYWORD_MAX_LENGTH,
    GUI_DOWNLOAD_MIN_COUNT,
    GUI_DOWNLOAD_MAX_COUNT,
)

__all__ = [
    'Settings',
    'settings',
    'MAX_LOG_ENTRIES',
    'LOG_ROTATION_SIZE',
    'LOG_RETENTION_DAYS',
    'DEFAULT_PAGE_SIZE',
    'MAX_EMPTY_PAGES',
    'MAX_CONSECUTIVE_EMPTY',
    'DEFAULT_CRAWL_DELAY',
    'DEFAULT_MAX_PAGES',
    'DEFAULT_CHUNK_SIZE',
    'DEFAULT_MAX_THREADS',
    'DEFAULT_MAX_RETRIES',
    'DEFAULT_RETRY_DELAY',
    'DEFAULT_TIMEOUT',
    'GUI_REFRESH_INTERVAL_RUNNING',
    'GUI_REFRESH_INTERVAL_IDLE',
    'GUI_KEYWORD_MIN_LENGTH',
    'GUI_KEYWORD_MAX_LENGTH',
    'GUI_DOWNLOAD_MIN_COUNT',
    'GUI_DOWNLOAD_MAX_COUNT',
]